"""
Alembic environment for the whatsapp_inbox module.

Auto-generated by ModuleRuntime. Uses per-module version table: alembic_whatsapp_inbox.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.core.db.base import Base

# Import module models so Alembic can detect them
from whatsapp_inbox.models import (  # noqa: F401
    EmployeeWhatsAppLink,
    InboxRequest,
    WhatsAppConversation,
    WhatsAppInboxSettings,
    WhatsAppMessage,
)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Per-module version table
VERSION_TABLE = "alembic_whatsapp_inbox"


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (generate SQL)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        version_table=VERSION_TABLE,
        include_object=_include_whatsapp_inbox_only,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (execute against DB)."""
    connectable = context.config.attributes.get("connection", None)
    if connectable is None:
        connectable = async_engine_from_config(
            config.get_section(config.config_ini_section),
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table=VERSION_TABLE,
            include_object=_include_whatsapp_inbox_only,
        )
        with context.begin_transaction():
            context.run_migrations()


def _include_whatsapp_inbox_only(object, name, type_, reflected, compare_to):
    """Only include tables belonging to the whatsapp_inbox module."""
    if type_ == "table":
        return name.startswith("whatsapp_inbox_")
    return True


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
